import { StyleSheet } from 'react-native';
import { Colors } from '../../../utils/colors';

export default StyleSheet.create({
  innerContainer: {
    alignItems: 'center',
    borderRadius: 20,
    backgroundColor: 'transparent',
    borderColor: Colors.yellow,
    borderWidth: 2,
    marginVertical: 20,
    marginHorizontal: 60,
  },
  titleText: {
    shadowColor: Colors.white,
    shadowRadius: 10,
    shadowOpacity: 1,
    shadowOffset: { width: 5, height: 5 },
    fontWeight: '900',
    fontSize: 20,
    color: Colors.white,
    paddingVertical: 20,
    letterSpacing: 2,
  },
  innerContainerCharacterButton: {
    alignItems: 'center',
    borderRadius: 10,
    backgroundColor: 'transparent',
    borderColor: Colors.yellow,
    borderWidth: 2,
    margin: 5,
    width: 110,
  },
  innerContainerCharacterButtonBorder: {
    borderColor: Colors.green,
  },
  titleTextCharacterButton: {
    shadowColor: Colors.white,
    shadowRadius: 10,
    shadowOpacity: 1,
    shadowOffset: { width: 5, height: 5 },
    fontWeight: '500',
    fontSize: 12,
    color: Colors.white,
    paddingVertical: 10,
    paddingHorizontal: 3,
    letterSpacing: 1,
  },
  favoritesBadge: {
    position: 'absolute',
    backgroundColor: Colors.black,
    right: -5,
    top: -10,
    borderRadius: 50,
    borderColor: Colors.yellow,
    borderWidth: 1,
    width: 30,
    height: 25,
    alignItems: 'center',
  },
  favoritesBadgeText: {
    color: Colors.white,
    fontSize: 18,
  },
});
